### ISSUE TITLE
Does not work with React-Native-Web

### ISSUE THREAD

**Issue by dgillier** [jfilter/react-native-onboarding-swiper#123] opened 2022-01-31 17:01 UTC
Got multiple errors : ""export 'ViewPropTypes' was not found in 'react-native-web/dist/index'"  when I tried to use use with React-Native-Web...

Any solution out there ?

Thanks, denis

**Comment by jfilter** [comment] 2022-01-31 20:44
This is a duplicate of https://github.com/jfilter/react-native-onboarding-swiper/issues/83.

**Closed by jfilter** 2022-01-31 20:44 UTC
